language: node_js
node_js:
- stable
sudo: false
script: npm run $COMMAND
before_script:
- npm run lint
env:
  matrix:
  - COMMAND=test
  - COMMAND=test-browser
  global:
  - secure: bVrN0fcDQx8yNsEH9fA4bkJGlYZ8X0eaHwKqa4DCkBITlkt7X7AnLP3Zv7ZidA9s+oXSVWIsDLGd/UxADG8g04jTXbsYIzQade0G1nU5cwl6vThUwk/TNZqYfqvD/5ay8zzzM9FU80wr1t27NAzFVamxw+mZZV46+FwUq8Rx23xORiZNqWOHyHJFXykkvj9yNI+y1KqdyAxaqeA9AISwwQO7sVRDNrQSiARQxyWUPcj0ERoUOD7Dfz9Ad/IjHnk8UGnqg4OEETOw2xuWD5Mq6z5xJApXl7NFCsmpOIX4ADLdsjXHBk4FSyF7Jn3R6R2zMnNGO5WQ89Vhn9ZbqcijeMTZ8iAxFz+RKoDdLnLr261G6h33l0BIDyqXN9D3HoEUCYk1CxEsusPZYRFm/PMnqnetSdFwmxzkz3gyNZ81OuRs5P6MgBoewWl8+bciSxR76kziz+xDVThs+UWyrWrEAy8xArekHKAwRR6BlwxVoV8zH+ZWgVBVzKJt5K/rIRZqj1cRHcOgoggVH8z91XS4A26uQ8nj7jKXZ56DVcVGaeMqa3bvD/BYhfe8dP+zxaoYr7MZEyTcSGjk1uqGsbbMgmlMIPG4t0i6V2mhUsnoJwLHiY6pXJzEK85tQNMno3AJhEUry9cpAa+O3GXFj9MpBPTR5i3q2+zCyfsrzNBD1ok=
  - secure: xl0o3eu71ijatdzJLfZrJr/Vu+74UmHl8dtl4CC4a4az6T4jU5O+IPjBFSpchFFzOs9uVm66GK7c24AprDaE+ce2g7n6Q9grzbQDOQgFL28W4cXHhqkYuMpsMu0uU370GZWT7+1SSNGKmliUZI8NGHA9e3BaHzrR1THrHD8E1Tu8hj+eEL9oNz2ZyFTG8STNK30iGNid7u9j7ffmdzzpaYvoumxIKqwu+71f+hAs9K4R59LKxrspYCjiSJp5AhgxKNLdom9bYW93EyJnfoPAyjZJygZD1GgMCmGejeo5PQXyDEaEEw6JEBCji7DulieVqhp1XzAD0gjE5h6T/O/OtAPjmaVTCjHXp7tru8NoKrY6OZZo8UQLR+bIXc8d2hOe+D/OS6ujpQ03kBchq+DWdXTrF7rTG0sVcTP7qx+X8iKX0dGHP6JyyGF3106yAkBhWNFAGqcP2ZpORKNmsMq4Z0zz5sTE2e0UJAgbGheTJIGXhO8t5reB8bKKg2/qNOG37WTSBspXgLEhomyB68sJiPW/n1rWVVjYBLj5E+TIm+dtSVyqPNxz2x6iovEy7guebrzXbMDKE+ttlo1m6g+TlB8CZHTJdwlNcA87NacnWaNxuLdXyCqyYiuZUypqRkcDGeSb9Pw+2zZ+Qgo0joWrutO8yezvxogfvOldNvqIUbY=
branches:
  only:
  - master
