ui: mocha-bdd
browsers:
  - name: chrome
    version: 49..latest
  - name: firefox
    version: 52..latest
  - name: safari
    version: 10..latest
  - name: microsoftedge
    version: 14..latest
  - name: iphone
    version: latest
  - name: ipad
    version: latest
  - name: android
    version: latest
concurrency: 4
tunnel:
  type: ngrok
  bind_tls: true
