ui: mocha-bdd
browsers:
  - name: chrome
    version: 42..latest
  - name: firefox
    version: 45..latest
  - name: safari
    version: 8..latest
  - name: microsoftedge
    version: 14..latest
  - name: iphone
    version: '8.4..latest'
  - name: ipad
    version: '8.4..latest'
  - name: android
    version: 5.0..latest
